openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Empresa API
  description: API que manipula os dados de uma empresa lista em bolsa
- name: Bolsa API
  description: API que manipula os dados de uma Bolsa de Valores
- name: Titulo API
  description: API que manipula os dados de um titulo de valor
- name: Negócio API
  description: API que manipula os dados de uma negociação de um título
- name: Nota de Corretagem API
  description: API que manipula os dados de uma nota de corretagem
- name: Corretora API
  description: API que manipula os dados das Corretoras.
paths:
  /corretoras/{id}:
    get:
      tags:
      - Corretora API
      operationId: findCorretora
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorretoraOutput'
    put:
      tags:
      - Corretora API
      operationId: fullUpdateCorretora
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Corretora'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorretoraOutput'
    patch:
      tags:
      - Corretora API
      operationId: incremetalUpdateCorretora
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Corretora'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorretoraOutput'
  /titulos:
    get:
      tags:
      - Titulo API
      operationId: listTitulos
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TituloOutput'
    post:
      tags:
      - Titulo API
      description: Cria um titulo de valor negociável
      operationId: createTitulo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TituloInput'
        required: true
      responses:
        "200":
          description: Caso o cadastro do título tenha sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TituloOutput'
  /notas:
    get:
      tags:
      - Nota de Corretagem API
      operationId: listNotaCorretagem
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NotaCorretagemOutput'
    post:
      tags:
      - Nota de Corretagem API
      description: Cria uma nota de corretagem
      operationId: createNotaCorretagem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotaCorretagemInput'
        required: true
      responses:
        "200":
          description: Caso a nota de corretagem seja cadastrada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotaCorretagemOutput'
  /negocios:
    get:
      tags:
      - Negócio API
      operationId: listNegocios
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NegocioOutput'
    post:
      tags:
      - Negócio API
      description: Cria uma negociação de um titulo
      operationId: createNegocio
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NegocioInput'
        required: true
      responses:
        "200":
          description: Caso o cadastro do negócio tenha sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NegocioOutput'
  /empresas:
    get:
      tags:
      - Empresa API
      operationId: listEmpresas
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmpresaOutput'
    post:
      tags:
      - Empresa API
      operationId: createEmpresa
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmpresaInput'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmpresaOutput'
  /corretoras:
    get:
      tags:
      - Corretora API
      description: Lista todas as corretoras
      operationId: listCorretoras
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CorretoraOutput'
    post:
      tags:
      - Corretora API
      operationId: createCorretora
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CorretoraInput'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorretoraOutput'
  /bolsas:
    get:
      tags:
      - Bolsa API
      description: Lista todas as bolsas
      operationId: listBolsas
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BolsaOutput'
    post:
      tags:
      - Bolsa API
      operationId: createBolsa
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BolsaInput'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BolsaOutput'
  /corretoras/situacao:
    get:
      tags:
      - Corretora API
      operationId: listCorretorasByStatus
      parameters:
      - name: status
        in: query
        required: true
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CorretoraOutput'
components:
  schemas:
    Corretora:
      required:
      - cnpj
      - dataCadastro
      - nome
      - status
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        dataCadastro:
          type: string
          format: date-time
        dataFinalizacao:
          type: string
          format: date-time
        cnpj:
          type: string
        status:
          type: boolean
      description: Classe que representa uma corretora de valores
    CorretoraOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        dataCadastro:
          type: string
          format: date-time
        dataFinalizacao:
          type: string
          format: date-time
        cnpj:
          type: string
        status:
          type: boolean
    TituloInput:
      required:
      - acao
      - ativo
      - codigo
      - dataInicialNegociacao
      - idBolsa
      - idEmpresa
      - opcao
      type: object
      properties:
        idBolsa:
          type: integer
          format: int64
        ativo:
          type: boolean
        idEmpresa:
          type: integer
          format: int64
        codigo:
          type: string
        dataInicialNegociacao:
          type: string
          format: date-time
        dataFinalNegociacao:
          type: string
          format: date-time
        strike:
          type: number
        acao:
          type: boolean
        opcao:
          type: boolean
    BolsaOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        sigla:
          type: string
        ativo:
          type: boolean
        dataCriacao:
          type: string
          format: date-time
        dataFinalizacao:
          type: string
          format: date-time
    EmpresaOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        cnpj:
          type: string
        ativo:
          type: boolean
        dataCriacao:
          type: string
          format: date-time
        dataFinalizacao:
          type: string
          format: date-time
    TituloOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        bolsa:
          $ref: '#/components/schemas/BolsaOutput'
        ativo:
          type: boolean
        empresa:
          $ref: '#/components/schemas/EmpresaOutput'
        codigo:
          type: string
        dataInicialNegociacao:
          type: string
          format: date-time
        dataFinalNegociacao:
          type: string
          format: date-time
        strike:
          type: number
        acao:
          type: boolean
        opcao:
          type: boolean
    NegocioInput:
      required:
      - idTitulo
      - tipoMercado
      - tipoNegocio
      type: object
      properties:
        idTitulo:
          type: integer
          format: int64
        quantidade:
          minimum: 1
          type: integer
          format: int32
        preco:
          type: number
        tipoNegocio:
          type: string
          enum:
          - COMPRA
          - VENDA
        tipoMercado:
          type: string
          enum:
          - VISTA
          - OPCAO_DE_COMPRA
          - OPCAO_DE_VENDA
          - EXERCICIO_OPCAO_DE_COMPRA
          - EXERCICIO_OPCAO_DE_VENDA
    NotaCorretagemInput:
      required:
      - idCorretora
      - negocios
      type: object
      properties:
        idCorretora:
          type: integer
          format: int64
        taxasImpostos:
          type: number
        irrf:
          type: number
        negocios:
          type: array
          items:
            $ref: '#/components/schemas/NegocioInput'
    Bolsa:
      required:
      - ativo
      - dataCriacao
      - nome
      - sigla
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        sigla:
          type: string
        ativo:
          type: boolean
        dataCriacao:
          type: string
          format: date-time
        dataFinalizacao:
          type: string
          format: date-time
      description: Classe que representa a bolsa onde está sendo negociado
    Empresa:
      required:
      - ativo
      - cnpj
      - dataCriacao
      - nome
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        cnpj:
          type: string
        ativo:
          type: boolean
        dataCriacao:
          type: string
          format: date-time
        dataFinalizacao:
          type: string
          format: date-time
      description: Classe que representa uma empresa listada em bolsa
    Negocio:
      required:
      - tipoMercado
      - tipoNegocio
      type: object
      properties:
        id:
          type: integer
          format: int64
        titulo:
          $ref: '#/components/schemas/Titulo'
        quantidade:
          minimum: 1
          type: integer
          format: int32
        preco:
          type: number
        tipoNegocio:
          type: string
          enum:
          - COMPRA
          - VENDA
        tipoMercado:
          type: string
          enum:
          - VISTA
          - OPCAO_DE_COMPRA
          - OPCAO_DE_VENDA
          - EXERCICIO_OPCAO_DE_COMPRA
          - EXERCICIO_OPCAO_DE_VENDA
        valorNegociado:
          type: number
      description: Classe que representa uma negociação em uma nota de corretagem
    NotaCorretagemOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        corretora:
          $ref: '#/components/schemas/Corretora'
        taxasImpostos:
          type: number
        irrf:
          type: number
        negocios:
          type: array
          items:
            $ref: '#/components/schemas/Negocio'
    Titulo:
      required:
      - codigo
      type: object
      properties:
        id:
          type: integer
          format: int64
        bolsa:
          $ref: '#/components/schemas/Bolsa'
        empresa:
          $ref: '#/components/schemas/Empresa'
        codigo:
          type: string
        dataInicialNegociacao:
          type: string
          format: date-time
        dataFinalNegociacao:
          type: string
          format: date-time
        strike:
          type: number
        ativo:
          type: boolean
        acao:
          type: boolean
        opcao:
          type: boolean
      description: Classe que representa um titulo de valor negociavel
    NegocioOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        titulo:
          $ref: '#/components/schemas/Titulo'
        quantidade:
          type: integer
          format: int32
        preco:
          type: number
        valorNegociado:
          type: number
        tipoNegocio:
          type: string
          enum:
          - COMPRA
          - VENDA
        tipoMercado:
          type: string
          enum:
          - VISTA
          - OPCAO_DE_COMPRA
          - OPCAO_DE_VENDA
          - EXERCICIO_OPCAO_DE_COMPRA
          - EXERCICIO_OPCAO_DE_VENDA
    EmpresaInput:
      required:
      - ativo
      - cnpj
      - nome
      type: object
      properties:
        nome:
          type: string
        cnpj:
          type: string
        dataCriacao:
          type: string
          format: date-time
        ativo:
          type: boolean
        dataFinalizacao:
          type: string
          format: date-time
    CorretoraInput:
      required:
      - ativo
      - cnpj
      - nome
      type: object
      properties:
        nome:
          type: string
        cnpj:
          type: string
        ativo:
          type: boolean
        dataCadastro:
          type: string
          format: date-time
        dataFinalizacao:
          type: string
          format: date-time
    BolsaInput:
      required:
      - ativo
      - nome
      - sigla
      type: object
      properties:
        nome:
          type: string
        sigla:
          type: string
        ativo:
          type: boolean
        dataCriacao:
          type: string
          format: date-time
        dataFinalizacao:
          type: string
          format: date-time
